### ISSUE TITLE
EVS pcap to wav file conversion using MediaTest run with error "unknown sample rate"

### ISSUE THREAD

**Issue by yinbao2000** [signalogic/SigSRF_SDK#1]
**Execution environment (ubuntu 14.04):**

`yin@ubuntu:~$ uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
`

**root@ubuntu:/usr/local/Signalogic_2017v6/DirectCore/apps/SigC641x_C667x/mediaTest# ./mediaTest -M0 -cx86 -ipcaps/EVS_13.2_16000.pcap -oevs_compact.wav -Csession_config/pcap_file_test_single**
SigSRF media transcoding and codec test and demo program for x86 and/or coCPU platforms, Rev 2.1, Copyright (C) Signalogic 2015-2017
Using demo only library versions
userSpecified = {clock = 0 MHz, Target Executable = , Card Type = x86, Core List = 0x00000000, Algorithm Flag = -1}
cimGetCmdLine: Platform designator = x86
Number of concurrent streams = 1
Config file = session_config/pcap_file_test_single
Input RTP file[0] is pcaps/EVS_13.2_16000.pcap
Output media file[0] is evs_compact.wav
Source IP addr[0] = 0xa000165, port[0] = 10240, MAC addr[0] = ffeeddccbb
Destination IP addr[0] = 0xa00010a, port[0] = 45056, MAC addr[0] = aabbccddee
Mode[0] = one-shot: load file, run
Transfer mode[0] = File download
Running in x86 mode
x86 mediaTest start
x86 pkt test start
Opening 1 input pcap file(s)
Opened pcap input file: pcaps/EVS_13.2_16000.pcap
Opened audio output file: evs_compact.wav
Opening session config file: session_config/pcap_file_test_single
**pktlib.c:390 ERROR: sample rate unknown**
Failed to create a session, continuing test with already created sessions
Failed to create any sessions, exiting test
x86 pkt test end
x86 mediaTest end
Process 5493 finished
root@ubuntu:/usr/local/Signalogic_2017v6/DirectCore/apps/SigC641x_C667x/mediaTest#

**Session file used** (attached in zip file: session_config/pcap_file_test_single):

session_data_start

term1.local_ip=192.168.0.1
term1.local_port=6154
term1.remote_ip=192.168.0.3
term1.remote_port=10242
term1.media_type=voice
term1.codec_type=EVS
term1.bitrate=13200
term1.ptime=20
term1.rtp_payload_type=127
term1.dtmf_type=NONE
term1.dtmf_payload_type=NONE
**term1.evs_sample_rate=16000** 
term1.evs_header_full=1

end_of_session_data

[session_and_pcap_file.zip](https://github.com/signalogic/SigSRF_SDK/files/1432028/session_and_pcap_file.zip)

**Comment by signalogic** [comment]
Yin Bao-

First can you make sure you have downloaded and installed the most recent demo .rar ?  In your screen output the version is showing 2.1, it should be 2.2.  Also the EVS_13.2_16000.pcap file has been renamed to evs_16khz_13200bps_FH_IPv4.pcap.

Additional notes:

1) With the new .rar file, the first command line to try is:

./mediaTest -M0 -cx86 -ipcaps/evs_16khz_13200bps_FH_IPv4.pcap -oevs_16khz_13200bps_FH_IPv4.wav -Csession_config/pcap_file_test_config -L

and verify that works.  Does it work ok ?

2) In your cmd line, you used the output name "compact.wav", but the input pcap has full header (FH) format, not compact header.  You could use the output name "full_header.wav" if you want.  Do you have your own pcap containing EVS RTP packets in compact header format ?

3) The "pcap_file_test_single" file inside the .zip file you attached is not a session config file.  It is very large (389 kB), and some other format.

4) If you have only term1 defined in your session config file, it should still work fine.  For example I created yinbao_evs_test_config (attached with .txt extension) and ran this cmd line:

./mediaTest -M0 -cx86 -ipcaps/evs_16khz_13200bps_FH_IPv4.pcap -oyinbao_test.wav -Csession_config/yinbao_evs_test_config -L

and mediaTest output looks as follows:

Running in x86 mode, no coCPU cores specified
x86 mediaTest start
x86 pkt test start
Opening session config file: session_config/yinbao_evs_test_config
1 session(s) found in config file
Opened pcap input file: pcaps/evs_16khz_13200bps_FH_IPv4.pcap
Opened audio output file: yinbao_test.wav
Creating session 0
WARNING: DSCreateSession, term2 sample rate unknown, defaulting to 8 kHz
Created session handle 0
Created 1 decoding session(s)
Buffer add rate for input stream[0] = 50 tps
Starting processing loop, press 'q' to exit
Packets input + read 3820, buffered 3676, pulled 3676, decoded 3676
Exiting test
Deleting session 0
Number of packets input + read = 3820, buffered = 3676, pulled = 3676, decoded = 3676
Writing pcap and jitter buffer stats to log file yinbao_test_log.txt
x86 pkt test end
x86 mediaTest end
Process 52853 finished

Note the warning message and default sampling rate (G711 format is used as the default if term2 is not defined).  The output pcap looked fine and output .wav file sounded clear.  I've attached the log file also (yinbao_test_log.txt)

-Jeff

[yinbao_evs_test_config.txt](https://github.com/signalogic/SigSRF_SDK/files/1432688/yinbao_evs_test_config.txt)
[yinbao_test_log.txt](https://github.com/signalogic/SigSRF_SDK/files/1432689/yinbao_test_log.txt)

**Comment by signalogic** [comment]
Docker container examples, including EVS pcaps, are at:

https://github.com/signalogic/SigSRF_SDK/blob/master/mediaTest_readme.md#user-content-dynamicsessioncreation
