### ISSUE TITLE
Convert EVS Pcap to Wav file using MediaTest

### ISSUE THREAD

**Issue by obfstr** [signalogic/SigSRF_SDK#3]
I am trying to convert EVS pcap to wav file using mediaTest.
Command used for pcap to wav conversion is

./mediaTest -M0 -cx86 -ipcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -otest.wav -Csession_config/pcap_file_test_config

THe output of this command is:
```

Using demo-only library versions
mediaTest: SigSRF media transcoding, codec, speech recognition, and packet streaming analysis, test, and measurement program for x86 and/or coCPU platforms v2.9.10 
Copyright (C) Signalogic 2015-2024 
  SigSRF libraries in use: DirectCore v4.1.5 DEMO, pktlib v3.6.0 DEMO, streamlib v1.11.0 DEMO, voplib v1.6.13 DEMO-HC, alglib v1.2.6, diaglib v1.7.0, cimlib v2.1.1 
userSpecified = {Platform Designator = x86, Clock = 2806.328 MHz, coCPU Core List = N/A, coCPU Executable = N/A}
cimGetCmdLine:  Platform designator = x86
		Number of concurrent streams = 1
		Config file = session_config/pcap_file_test_config
		Input RTP file[0] is pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap
		Output media file[0] is test.wav
		Buffer add interval [0] (msec) = -nan
		Source IP addr[0] = 0xa000165, port[0] = 10240, MAC addr[0] = ffeeddccbb
		Destination IP addr[0] = 0xa00010a, port[0] = 45056, MAC addr[0] = aabbccddee
		Mode[0] = one-shot:  load file, run
		Transfer mode[0] = File download
 mediaTest INFO: event log setup complete, log file sig_lib_event_log.txt, cmd line ./mediaTest -M0 -cx86 -ipcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -otest.wav -Csession_config/pcap_file_test_config  
Running on x86 cores, no coCPU cores specified
x86 mediaTest() entry point process 
x86 mediaTest end process 
Process 215 finished


```

**Note: NO wav file is generated**

I also tried the mediaTest command without M0 flag:

./mediaTest -cx86 -ipcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -otest.wav -Csession_config/pcap_file_test_config

The output is as follows:
```

Using demo-only library versions
mediaTest: SigSRF media transcoding, codec, speech recognition, and packet streaming analysis, test, and measurement program for x86 and/or coCPU platforms v2.9.10 
Copyright (C) Signalogic 2015-2024 
  SigSRF libraries in use: DirectCore v4.1.5 DEMO, pktlib v3.6.0 DEMO, streamlib v1.11.0 DEMO, voplib v1.6.13 DEMO-HC, alglib v1.2.6, diaglib v1.7.0, cimlib v2.1.1 
userSpecified = {Platform Designator = x86, Clock = 4365.709 MHz, coCPU Core List = N/A, coCPU Executable = N/A}
cimGetCmdLine:  Platform designator = x86
		Number of concurrent streams = 1
		Config file = session_config/pcap_file_test_config
		Input RTP file[0] is pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap
		Output media file[0] is test.wav
		Buffer add interval [0] (msec) = -nan
		Source IP addr[0] = 0xa000165, port[0] = 10240, MAC addr[0] = ffeeddccbb
		Destination IP addr[0] = 0xa00010a, port[0] = 45056, MAC addr[0] = aabbccddee
		Mode[0] = one-shot:  load file, run
		Transfer mode[0] = File download
 mediaTest INFO: event log setup complete, log file sig_lib_event_log.txt, cmd line ./mediaTest -cx86 -ipcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -otest.wav -Csession_config/pcap_file_test_config  
Invalid cmd line options for x86, make sure: 
  one or more -i and -o (input and output) options are correctly specified 
  one -C (config file) is correctly specified 
  one -c option (platform type) is given and either none or only one -M (operating mode) option is given 
  debug info:  codec test = 0, x86 frame test = 0, x86 pkt test = 0, pcap extract = 0, gpx process = 0 
To see the full list of cmd line options, run ./mediaTest -h 
Process 216 finished


```

**Note: No wav file is generated**

THe config file used is as follows:
```

[start_of_session_data]

term1.local_ip = 192.168.0.1
term1.local_port = 6154
term1.remote_ip = 192.168.0.3
term1.remote_port = 10242
term1.media_type = voice
term1.codec_type = EVS
term1.bitrate = 13200  # in bps
term1.ptime = 20  # in msec
term1.rtp_payload_type = 127
term1.dtmf_type = NONE
term1.dtmf_payload_type = NONE
term1.sample_rate = 16000  # in Hz
term1.header_format = 1  # for EVS, 0 = CH format, 1 = FH format
## term2.dtx_handling = -1  # -1 disables DTX handling

[end_of_session_data]


```

**Comment by signalogic** [comment]
Hi Syed, can you try this command line:

  ` mediaMin -cx86 -i../pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -L -d0xc11 -r20`
   
this should produce both a pcap and wav file (about 4.7MB) in the mediaMin subfolder (located under the mediaTest folder).

I ran that test and audio quality is perfect - Wireshark shows 20.27 msec average packet delta and max jitter of 0.04 msec.

In the meantime, I will look at the mediaTest command line and see why it didn't generate a wav file. Also if you have any other trouble with example command lines on the Github page, let me know ASAP

Thanks, Jeff

**Comment by signalogic** [comment]
Also, you can run:

` mediaMin -cx86 -i../pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -L -d0xc11 -r0.5`
 
to reduce processing time from 5 min (real-time) to about 7 sec

**Comment by obfstr** [comment]
I ran the command 
`mediaMin -cx86 -i../pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -L -d0xc11 -r0.5`

and it ran successfully, wav file is also generated and it is perfectly clear.
I also tested my pcaps of EVS AMRWB IO 23850 but the wav file generated contained some noise.
I also encountered some errors during the execution of EVS AMRWB IO pcap.
The command i used for the execution of EVS AMRWB IO pcap is:

`mediaMin -cx86 -i/home/Codecs/EVS23/2024-03-04_10-23-53__971566857734__971542457837__ID14379613286.pcap -L -d0xc11 -r0.5`

The errors i encountered are:
```
00:00:00.444.315 WARNING: DSCodecDecode() says failed to correctly parse ToC byte in EVS payload, first byte of input = 0xf0, ToC[1] = 0x2a, payloadSize[1] = -1, fAMRWB_IOMode = 1 
00:00:00.444.358 ERROR: pkt/media thread 0 says DSCodecDecode() returned error condition, hSession = 1, chnum = 2, pyld_len = 60, hCodec = 4 
Pushed pkts 1608, pulled pkts 2024j 2023x 981s  Pkts recv 1791 buf 1791 jb 2216 xc 2215 sg 1103 sent 2215 mnp 159 175 -1 pd 20.00 20.08 -1.007 -1.00
SigSRF EVS decoder says error in EVS(AMRWBIO) FT ToC header 0xb3, num_bits = 285, pyld_len = 37, payload[0] = 0xb3 
Pushed pkts 2003, pulled pkts 2426j 2425x 1182s	Pkts recv 1950 buf 1950 jb 2375 xc 2374 sg 1187 sent 2374 mnp 159 175 -1 pd 20.00 19.56 -1.00
SigSRF EVS decoder says error in EVS(AMRWBIO) FT ToC header 0xbf, num_bits = 0, pyld_len = 1, payload[0] = 0xbf 

``` 

I also tried to generate wav file of EVS AMRWB IO by following the instructions on this link: [3GPP Reference Code Notes](https://github.com/signalogic/SigSRF_SDK/blob/master/mediaTest_readme.md#3gpp-reference-code-notes)

But when i ran the EVS Decoder using the following command:

`./EVS_dec -mime -no_delay_cmp 16 sample.cod sample.raw`

I enountered the error:
`Error in EVS(AMRWBIO)  FT ToC header(ff)`

Also tried to generate the wav file of pcap you have provided in the pcaps folder: **AMRWB-23.85kbps-20ms_bw.pcap** Using the command

`mediaMin -cx86 -i../pcaps/AMRWB-23.85kbps-20ms_bw.pcap -L -d0xc11 -r0.5
`

But the error encountered are:

```
DSGetPacketInfo() returns error value for new session packet, no codec estimation performed, malformed UDP/RTP packet, IP hdr len = 20, rtp pyld len = 61, rtp padding size = 0, pkt len = 105, rtp pyld type = 101. Possibly try ALLOW_OUTOFSPEC_RTP_PADDING flag in cmd line -dN argument 
DSGetPacketInfo() returns error value for new session packet, no codec estimation performed, malformed UDP/RTP packet, IP hdr len = 20, rtp pyld len = 61, rtp padding size = 0, pkt len = 105, rtp pyld type = 101. Possibly try ALLOW_OUTOFSPEC_RTP_PADDING flag in cmd line -dN argument 
DSGetPacketInfo() returns error value for new session packet, no codec estimation performed, malformed UDP/RTP packet, IP hdr len = 20, rtp pyld len = 61, rtp padding size = 0, pkt len = 105, rtp pyld type = 101. Possibly try ALLOW_OUTOFSPEC_RTP_PADDING flag in cmd line -dN argument 
DSGetPacketInfo() returns error value for new session packet, no codec estimation performed, malformed UDP/RTP packet, IP hdr len = 20, rtp pyld len = 61, rtp padding size = 0, pkt len = 105, rtp pyld type = 101. Possibly try ALLOW_OUTOFSPEC_RTP_PADDING flag in cmd line -dN argument 

```
**Note: No wav file is generated (In case of AMRWB-23.85kbps-20ms_bw.pcap)**

If you have a sample of EVS AMRWB IO 23850 pcap, kindly share it for testing purposes.

Log file for the EVS AMRWB IO pcap and AMRWB-23.85kbps-20ms_bw.pcap is attached:

EVS AMRWB IO pcap log file: 
[2024-03-04_10-23-53__971566857734__971542457837__ID14379613286_event_log.txt](https://github.com/signalogic/SigSRF_SDK/files/14864472/2024-03-04_10-23-53__971566857734__971542457837__ID14379613286_event_log.txt)

AMRWB-23.85kbps-20ms_bw.pcap log file:
[AMRWB-23.85kbps-20ms_bw_event_log.txt](https://github.com/signalogic/SigSRF_SDK/files/14864514/AMRWB-23.85kbps-20ms_bw_event_log.txt)

**Comment by signalogic** [comment]
Hi Syed yes we have several EVS AMR-WB IO mode pcaps, but they came from customers. What I can do is anonymize one of those, and replace the audio with some noise or silence, then I think we can share it. Let me check on that

Regarding the error message above:

00:00:00.444.315 WARNING: DSCodecDecode() says failed to correctly parse ToC byte in EVS payload, first byte of input = 0xf0, ToC[1] = 0x2a, payloadSize[1] = -1, fAMRWB_IOMode = 1

Can you try this form of mediaMin command:

 ` mediaMin -cx86 -ifilename.pcap -L -d0xc11 -r20 -C../session_config/EVS_AMR-WB_IO_mode_payload_shift`

and let me know ?  We have seen some EVS AMR-WB IO mode RTP streams "in the wild" that need a 2-bit payload shift (i.e. they are not correct per the EVS spec); the above command line addresses that. If that doesn't work, then can you send an example pcap to us via e-mail (info at signalogic dot com) ? We can figure out what's needed for mediaMin to decode it

**Comment by signalogic** [comment]
Hi Syed, regarding your test on the AMRWB-23.85kbps-20ms_bw.pcap file, first that is an AMR-WB pcap, not EVS AMR-WB compatibility mode. Second please use this mediaMin command:

  `mediaMin -cx86 -i../pcaps/AMRWB-23.85kbps-20ms_bw.pcap -r20 -L -d0x20000000000c11`

this sets the ALLOW_NONSTANDARD_RTP_PADDING flag, because that particular .pcap has padding in its RTP payloads that is not specified in its RTP headers (you can see the problem in Wireshark, which shows the payloads as DTMF events)

**Comment by obfstr** [comment]
I tested the EVS AMRWB IO packet captures using the command that you provided, and the generated WAV file is clear without any noise. 

Can you kindly elaborate on the issue of why we need a 2-bit payload shift? How are these RTP streams different from standard RTP streams? Is there any other way of handling these RTP streams?

**Comment by signalogic** [comment]
Hi Syed, thanks for letting us know your test results. It seems an endpoint or SBC-type entity out there has incorrectly implemented EVS AMR-WB IO payload encoding. We're not sure who yet, but counting your example we've now seen it half a dozen times or so. Maybe they are translating AMR-WB payloads into EVS compatibility mode and somehow misinterpreted the EVS spec, which is admittedly complicated when it comes to AMR-WB IO payload formatting. My guess is that in their internal testing they missed this bug because it's in their EVS common library so it's shared by both their encoder and decoder, but when in the wild other decoders can "see" it

To demonstrate this further, you can run the following mediaTest command:

  `mediaTest -cx86 -itest_files/stv16c.INP -otest_files/stv16c_16kHz_23850_full_header.pcap -Csession_config/evs_16kHz_23850bps_amrwb_io_full_header_config`

which generates an EVS AMR-WB IO mode pcap from one of the standard 3GPP test vector (raw audio) files, exactly per 3GPP spec, making no changes between encoder output and decoder input. Then run the following mediaMin command:

  `mediaMin -cx86 -i../test_files/stv16c_16kHz_23850_full_header.pcap -L -d0x08000c11 -r0.5`

which processes the pcap into wav and G711 pcap files, with no additional payload shift

**Comment by obfstr** [comment]
I generated the pcap file using the commands that you provided and the commands executed successfully. 
According to the specification of EVS AMRWB IO, the payload size of EVS AMRWB IO with bitrate of 23.85kbps is 60 bytes. After adding the 12 bytes of RTP payload, the total size is 72 bytes. 
In the pcap that you provided, the total size is 74 bytes. How is it 74 bytes? Shouldn't it be 72 bytes?
Can you kindly tell us how can we integrate the support of these non standard pcaps in our project. Can you recommend us any resource that we can follow to deal with these non standard pcaps as we did not find anything in the official specification.

The link to the official specification is attached [here](https://www.etsi.org/deliver/etsi_ts/126400_126499/126445/17.00.00_60/ts_126445v170000p.pdf).

**Comment by signalogic** [comment]
Hi Syed, for EVS AMR-IO mode 23850 bps RTP payload size, calculate as follows:

  60 (payload size in the spec, as you noted)
  If using full header format
     +1 ToC header byte
     +1 padding byte appended for collision avoidance with 24400 bps compact format

collision avoidance is discussed in spec section A.2.2.1.4.2, Zero padding for size collision avoidance

Note that Wireshark, when displaying stv16c_16kHz_23850_full_header.pcap generated by mediaTest, correctly interprets all packets, including SID and NO_DATA, implying that it "knows" about EVS collision avoidance

Re. your application support questions, one option is to use the demo versions of voplib and EVS .so's, for example you can look at the "hello_codec" reference app included in the .rar packages and Docker containers. Other options include licensed versions of the libs, or help in some form to modify your app at source code level. For those, is it possible to discuss privately ? Thanks

**Comment by obfstr** [comment]
Hello, I have tried to run the hello_codec reference app using the following command: The pcap given as input is of EVS AMRWB IO.

`./hello_codec -cx86 -i/home/EVS_AMRWB_IO.pcap -L -d0xc11 -r20 -C../session_config/EVS_AMR-WB_IO_mode_payload_shift`

The error encountered is:

```
ERROR: DSCodecEncode(), hCodec[0] param <= 0, voplib.c:615 
Processing frame 1...ERROR: DSCodecEncode(), hCodec[0] param <= 0, voplib.c:615 
Processing frame 2...ERROR: DSCodecEncode(), hCodec[0] param <= 0, voplib.c:615 
Processing frame 3...ERROR: DSCodecEncode(), hCodec[0] param <= 0, voplib.c:615 

```

**Comment by signalogic** [comment]
Hi Syed,

The hello_codec reference app doesn't handle command line file I/O. In hello_codec.c the comments show the following command line usage:

  ./hello_codec -cx86 -C../session_config/evs_16kHz_13200bps_config

so hopefully that runs without errors. The code creates some codec instances then does frame-by-frame encoding and decoding on an example waveform (from an array, not from a file).

The code is simple and can be integrated into your application that is already handling file or network I/O. Look for the set_codec_params() function to see how to set the CODEC_ENC_PARAMS and CODEC_DEC_PARAMS structs, which are then used when calling DSCodecCreate(). These APIs and structs are defined in voplib.h

**Comment by obfstr** [comment]
Hi Jeff, 

Thank you for cooperating with us. I am closing this issue as resolved.
